#!/bin/bash
PID=/tmp/shadowsocks.pid
RETVAL=$?
start(){
    if [ -f ${PID} ];then
        echo "already started"
        RETVAL=1
    else
        echo "start"
        #ss-local -c $SSCONFIGPATH/config.json -f ${PID}
        #ss-local --fast-open -A -c $SSCONFIGPATH/config.json -f ${PID}
        ss-local -A -c $SSCONFIGPATH/config.json -f ${PID}
        RETVAL=0
    fi
    return $RETVAL
}
stop(){
    if [ -f ${PID} ];then
        kill -9 $(cat ${PID})
        rm ${PID}
        echo "stop now"
        RETVAL=0
    else
        echo "not started"
        RETVAL=1
    fi
    return $RETVAL
}
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
esac
